commerce:
  prices:
    - "config - 1000: 20"
    - "config - 1001: 21"
    - "config - 1002: 22"
    - "config - 1003: 23"
    - "config - 1004: 24"
    - "config - 1005: 25"
    - "config - 1006: 26"
    - "config - 1007: 27"
    - "config - 1008: 28"
    - "config - 1009: 29"
    - "config - 1010: 201"
    - "config - 1011: 202"
    - "config - 1012: 203"
    - "config - 1013: 204"
    - "config - 1014: 205"
    - "config - 1015: 206"
    - "config - 1016: 207"
    - "config - 1017: 208"
    - "config - 1018: 209"
    - "config - 1019: 200"
    - "config - 1020: 30"
    - "config - 1021: 40"
    - "config - 1022: 50"
    - "config - 1023: 60"
    - "config - 1024: 70"
    - "config - 1025: 80"
    - "config - 1026: 90"
    - "config - 1027: 301"
    - "config - 1028: 302"
    - "config - 1029: 303"
    - "config - 1030: 304"
    - "config - 1031: 305"
    - "config - 1032: 306"
    - "config - 1033: 307"
    - "config - 1034: 308"
    - "config - 1035: 401"
    - "config - 1036: 402"
    - "config - 1037: 403"
    - "config - 1038: 404"
    - "config - 1039: 405"
    - "config - 1040: 406"
    - "config - 1041: 407"
    - "config - 1042: 408"
    - "config - 1043: 409"
    - "config - 1044: 410"
    - "config - 1045: 420"
    - "config - 1046: 430"
    - "config - 1047: 520"
    - "config - 1048: 620"
    - "config - 1049: 720"

logging:
  level:
    root: WARN
    org.springframework.web: WARN
    io.spring.cloud.samples: INFO
